version: 0.2

phases:
  install:
    commands:
      - echo "Installing..."
  build:
    commands:
      - echo "Build completed"  # No build needed for static sites

artifacts:
  files:
    - '**/*'
